---
- hosts: all
  become: yes

  vars_files:
    - variables.yml

  tasks:
    - name: Update packages
      apt:
        name:
          - curl
        state: latest
        update_cache: yes
        
    - name: Create odoo back and restore directory
      file:
        path: "{{ item }}"
        state: directory
        owner: bitnami
        group: odoo
        mode: 0775
      with_items:
          - /home/bitnami/odoo_backup
          - /home/bitnami/odoo_restore
    
    - name: Copy custom_addons directory
      copy:
        src: "../custom_addons"
        dest: "/home/bitnami/custom_addons"
        owner: bitnami
        group: odoo
        mode: 0775

    - name: Change odoo admin password in odoo.conf
      lineinfile:
        path: /opt/bitnami/odoo/conf/odoo.conf
        regexp: '^admin_passwd'
        line: "admin_passwd  = {{ odoo_admin_password }}"

    - name: Add custom_addons as addons_path to odoo.conf
      lineinfile:
        path: /opt/bitnami/odoo/conf/odoo.conf
        regexp: '^addons_path'
        line: 'addons_path = /opt/bitnami/odoo/addons,/home/bitnami/custom_addons'
        backup: yes

    - name: Ensure python modules are installed
      shell: "/opt/bitnami/odoo/venv/bin/python3 -m pip install dropbox botocore awscli boto3 paramiko"

    - name: Stop and disable timesyncd
      shell: "systemctl stop systemd-timesyncd; systemctl disable systemd-timesyncd"

    - name: Ensure chrony is present
      apt:  name=chrony state=present

    - name: Restart all odoo related services
      shell: "/opt/bitnami/ctlscript.sh restart"

    - name: Copy backup script
      copy:
        src: "../ssx-base-db-bkup.sh"
        dest: "/home/bitnami/ssx-base-db-bkup.sh"
        owner: bitnami
        group: odoo
        mode: 0775    

    - name: Add cron job to backup odoo
      cron:
        name: backup_odoo
        user: bitnami
        hour: '*/6'
        job: "/opt/bitnami/odoo/ssx-base-db-bkup.sh"
        state: present

