---
- hosts: all
  become: true

  vars_files:
    - variables.yml

  tasks:
    - name: Change odoo admin password in odoo.conf
      lineinfile:
        path: /opt/bitnami/odoo/conf/odoo.conf
        regexp: '^admin_passwd'
        line: "admin_passwd  = {{ odoo_admin_password }}"

    - name: Add custom_addons as addons_path to odoo.conf
      lineinfile:
        path: /opt/bitnami/odoo/conf/odoo.conf
        regexp: '^addons_path'
        line: 'addons_path = /opt/bitnami/odoo/addons,/home/bitnami/s3-odoo-terraform/custom_addons'
        backup: yes

    - name: Add database endpoints to odoo.conf
      lineinfile:
        path: /opt/bitnami/odoo/conf/odoo.conf
        regexp: '^db_host'
        line: 'db_host = {{ odoo_db_host }}'
    
    - name: Add postgres user to odoo.conf
      lineinfile:
        path: /opt/bitnami/odoo/conf/odoo.conf
        regexp: '^db_user'
        line: 'db_user = {{ odoo_db_user }}'

    - name: Add postgres password to odoo.conf
      lineinfile:
        path: /opt/bitnami/odoo/conf/odoo.conf
        regexp: '^db_password'
        line: 'db_password = {{ odoo_db_password }}'

    - name: Ensure python modules are installed
      shell: "/opt/bitnami/odoo/venv/bin/python3 -m pip install dropbox botocore awscli boto3 paramiko"

    