---
- hosts: all
  become: yes

  vars:
    ansible_python_interpreter: /usr/bin/python3


  tasks:
    - name: Add custom_addons as addons_path to odoo.conf
      replace:
        path: /opt/bitnami/odoo/conf/odoo.conf
        regexp: 'addons_path = /opt/bitnami/odoo/addons '
        replace: 'addons_path = /opt/bitnami/odoo/addons,/vagrant/custom_addons'
        backup: yes

    - name: Install bottle python package
      pip:
        name:
          - paramiko
          - dropbox
        extra_args: --upgrade

    - name: Restart all odoo related services
      shell: "/opt/bitnami/ctlscript.sh restart"

    - name: Stop and disable timesyncd
      shell: "systemctl stop systemd-timesyncd; systemctl disable systemd-timesyncd"

    - name: Ensure chrony is present
      apt:  name=chrony state=present

    - name: Restart chrony
      shell: "/etc/init.d/chrony restart"

    - debug: var=ansible_enp0s8.ipv4.address
