---
- hosts: all
  become: yes

  vars:
    ntp_enabled: true
    ntp_timezone: Africa/Accra

  roles:
    - geerlingguy.ntp

  tasks:
    - name: Create odoo_backup directory
      file:
        path: /home/bitnami/odoo_backup
        state: directory
        owner: odoo
        group: odoo
        mode: 0775

    - name: Create .aws directory
      file:
        path: /home/bitnami/.aws
        state: directory
        owner: bitnami
        group: bitnami


    - name: Copy AWS credential file to odoo server
      copy:
        src: ~/.aws/credentials
        dest: /home/bitnami/.aws/credentials

    - name: Add custom_addons as addons_path to odoo.conf
      replace:
        path: /opt/bitnami/odoo/conf/odoo.conf
        regexp: 'addons_path = /opt/bitnami/odoo/addons'
        replace: 'addons_path = /opt/bitnami/odoo/addons,/home/bitnami/custom_addons'
        backup: yes

    - name: Install necessary python libraries
      shell: "pip3 install --upgrade pip; pip3 install paramiko dropbox"

    - name: Restart all odoo related services
      shell: "/opt/bitnami/ctlscript.sh restart"

    - name: Set S3 backup cronjob
      cron:
        name: odoo_backup
        user: bitnami
        hour: '*/1'
        job: aws s3 sync /home/bitnami/odoo_backup s3://ssx-postgres-backups/ssx-restore/