---
- hosts: all
  become: yes

  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Add custom_addons as addons_path to odoo.conf
      lineinfile:
        path: /opt/bitnami/odoo/conf/odoo.conf
        regexp: '^addons_path'
        line: 'addons_path = /opt/bitnami/odoo/addons,/vagrant/custom_addons'
        backup: yes

    - name: Install bottle python package
      pip:
        name:
          - paramiko
          - dropbox
        extra_args: --upgrade

    - name: Replace a listen_addresses entry in postgresql.conf
      lineinfile:
        path: /opt/bitnami/postgresql/conf/postgresql.conf
        regex: '^listen_addresses'
        line: listen_addresses = '*'

    - name: Add pg_hba.conf entry for remote access
      lineinfile:
        path: /opt/bitnami/postgresql/conf/pg_hba.conf
        regexp: '^'
        line: 'host all all 10.51.1.0/24 md5'

    - name: Restart all services
      shell: "/opt/bitnami/ctlscript.sh restart"

    - debug: var=ansible_enp0s8.ipv4.address
