---
- hosts: all
  become: yes

  vars:
    ansible_python_interpreter: /usr/bin/python3
    odoo_admin_password: "bitnami"

  tasks:
    - name: Update packages
      apt:
        name:
          - curl
        state: latest
        update_cache: yes
        
    - name: Create odoo back and restore directory
      file:
        path: "{{ item }}"
        state: directory
        owner: bitnami
        group: odoo
        mode: 0775
      with_items:
          - /home/bitnami/odoo_backup
          - /home/bitnami/odoo_restore

    # - name: Copy odoo custom_addons directory
    #   copy:
    #     src: "../custom_addons"
    #     dest: "/home/bitnami/custom_addons"
    #     owner: bitnami
    #     group: odoo
    #     state: directory

    - name: Change odoo admin password in odoo.conf
      lineinfile:
        path: /opt/bitnami/odoo/conf/odoo.conf
        regexp: '^admin_passwd'
        line: "admin_passwd  = {{ odoo_admin_password }}"

    - name: Add custom_addons as addons_path to odoo.conf
      lineinfile:
        path: /opt/bitnami/odoo/conf/odoo.conf
        regexp: '^addons_path'
        line: 'addons_path = /opt/bitnami/odoo/addons,/home/bitnami/custom_addons'
        backup: yes

    - name: Ensure python modules are installed
      pip:
        name: ['boto3', 'botocore', 'awscli', 'paramiko', 'dropbox']
        state: latest

    - name: Simple GET operation to download latest restore db
      shell: "aws s3 cp s3://ssx-postgres-backups/ssx-restore/restore.zip /home/bitnami/odoo_restore/restore.zip"
      become_user: bitnami
      args:
        creates: /home/bitnami/odoo_restore/restore.zip   

    - name: Delete existing odoo database
      shell: "curl -F 'master_pwd=bitnami' -F 'name=ssx-base-db' http://localhost:8069/web/database/drop"
      ignore_errors: yes

    - name: Restore odoo db from zip file
      shell: "curl -F 'master_pwd=bitnami' -F backup_file=@/home/bitnami/odoo_restore/restore.zip -F 'copy=true' -F 'name=ssx-base-db' http://localhost:8069/web/database/restore"

    - name: Stop and disable timesyncd
      shell: "systemctl stop systemd-timesyncd; systemctl disable systemd-timesyncd"

    - name: Ensure chrony is present
      apt:  name=chrony state=present

    - name: Restart chrony
      shell: "/etc/init.d/chrony restart"


    - name: Restart all odoo related services
      shell: "/opt/bitnami/ctlscript.sh restart"
      
