---
- hosts: all
  become: yes

  vars:
    postgresql_version: '12'
    postgresql_service_state: started
    postgresql_service_enabled: true
    firewall_allowed_tcp_ports:
      - "22"
      - "5432"
    
    postgresql_hba_entries:
      - { type: host, database: all, user: all, address: '0.0.0.0/0', auth_method: md5 }

 
  pre_tasks:
    - name: Update package list
      apt: update_cache=yes cache_valid_time=3600

    - name: Upgrade all packages on servers
      apt: upgrade=dist

  roles:
    - role: geerlingguy.postgresql
    - role: geerlingguy.firewall

