---
- hosts: all
  become: yes

  vars_files:
    - vars.yml

  pre_tasks:
    - name: Update package list
      apt: update_cache=yes cache_valid_time=3600

    - name: Upgrade all packages on servers
      apt: upgrade=dist

  roles:
    - role: geerlingguy.postgresql
    - role: geerlingguy.firewall

