version: '3.9'
networks:
  app-network:
    driver: bridge

services:
  ssx-odoo:
    build: .
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      # - ./config:/etc/odoo
      - ./custom_addons:/mnt/extra-addons
    # environment:
    #   - HOST=${RDS_HOST}
    #   - USER=${RDS_USER}
    #   - PASSWORD=${RDS_PASSWORD}
    networks:
      - app-network

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    networks:
      - app-network
  nginx-lb:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - ssx-odoo
    networks:
      - app-network