version: '3.9'
services:
  ssx-odoo:
    image: odoo:15.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      # - ./config:/etc/odoo
      - ./custom_addons:/mnt/extra-addons
    # environment:
    #   - HOST=${RDS_HOST}
    #   - USER=${RDS_USER}
    #   - PASSWORD=${RDS_PASSWORD}

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo

  nginx-lb:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/sites-enabled:ro
    depends_on:
      - ssx-odoo