version: '3.9'
services:
  ssx-odoo:
    build: .
    ports:
      - "8069:8069"
    volumes:
      - ./custom_addons:/mnt/extra-addons
      - ./odoo-data:/var/lib/odoo

    environment:
      - HOST=${RDS_HOST}
      - USER=${RDS_USER}
      - PASSWORD=${RDS_PASSWORD}

  syslog-odoo:
    image: odoo:15.0
    ports:
      - "8068:8069"
    volumes:
      - ./custom_addons:/mnt/extra-addons
    environment:
      - HOST=${RDS_HOST}
      - USER=${RDS_USER}
      - PASSWORD=${RDS_PASSWORD}

volumes:
  odoo-data:
    driver: local
