version: '3.1'
services:
  web:
    image: odoo:latest
    ports:
      - "8069:8069"
    environment:
      - HOST=192.168.0.2
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - ./lightsail/custom_addons:/mnt/extra-addons
      - ./config:/etc/odoo

volumes:
  odoo-web-data:
  odoo-db-data: