version: '3.1'
services:
  web:
    image: odoo:15.0
    depends_on:
      - db
    ports:
      - "80:8069"
    volumes:
      - ./config:/etc/odoo
      - ./custom_addons:/mnt/extra-addons
    environment:
    - HOST=odoodatabase.c8wvdvkuvq0x.eu-central-1.rds.amazonaws.com
    - DB_NAME=postgres
    - USER=odoouser
    - PASSWORD=sLRXoul6FfeYSl7AzmrE

