version: '2.7'

networks:
  ssx_network:

volumes:
  ssx-db-data:
    external: true
    name: ssx-db-data
services:
  web:
    image: odoo:15.0
    depends_on:
      - mydb
    ports:
      - "8069:8069"
    environment:
    - HOST=mydb
    - USER=odoo
    - PASSWORD=myodoo
    volumes:
      # - odoo-web-data:/var/lib/odoo
      - ./custom_addons:/mnt/extra-addons
      - ./config:/etc/odoo
    networks:
      - ssx_network
  mydb:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=myodoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - ssx-db-data:/var/lib/postgresql/data
    networks:
      - ssx_network
